### ISSUE TITLE
TER upload error: missing dependency on supported TYPO3 version

### ISSUE THREAD

**Issue by mbrodala** [NamelessCoder/typo3-repository-client#1]
When trying to upload an extension currently an error like this occurs:

> SOAP error: Extension does not have a dependency for a supported version of TYPO3. See http://typo3.org/news/article/announcing-ter-cleanup-process/ for how to fix this.

The relevant [ext_emconf.php](https://github.com/pagemachine/cors/blob/5b566309899ec1451257baaf9c801b9479c5a5ce/composer.json) is perfectly fine though:

``` php
<?php

$EM_CONF[$_EXTKEY] = array(
  // ...
  'constraints' => array(
    'depends' => array(
      'typo3' => '6.2.0-6.2.99',
    ),
    // ...
  ),
);
```

A small debug within `ExtensionUploadPacker::createSoapData` also confirms that the dependency array has been built properly:

```
Array
(
    [0] => Array
        (
            [kind] => depends
            [extensionKey] => typo3
            [versionRange] => 6.2.0-6.2.99
        )

)
```

Does this actually work for someone ATM or are we affected by [this TER bug](https://forge.typo3.org/issues/61490)?

**Comment by fnagel** [comment]
Same issue here for https://github.com/fnagel/generic-gallery/commit/da491caea99202978cdd198a0ce022b80e1ca940

Yesterday identical dependencies worked for another extension without problems. It seems this could be a temporary TER issue.

**Comment by NamelessCoder** [comment]
I'm not sure what causes this but I suspect TER gets confused along the way. Both the SOAP XML and dependencies arrays are being built correctly.

VHS 2.3.0 was released this way, maybe there's a hint to be found in the emconf of that ext?

**Comment by fnagel** [comment]
It just makes no sense. I released this yesterday without any problems: https://github.com/fnagel/t3extblog/commit/d10760be3c34056342b2f80e071819e19a645c4f

I will try again, perhaps its just a temp issues... TER sometimes has its own magic.

**Comment by NamelessCoder** [comment]
Hint: you can use GitHub's webhook settings panel to re-dispatch the request. Maybe that works...

**Comment by fnagel** [comment]
Already tried that a few times for testing. 

@mbrodala How did you solve your problem?

**Comment by NamelessCoder** [comment]
This is just absolutely crazy - this from 30 seconds ago: https://github.com/NamelessCoder/uploadtest/commit/9208d4ad802a946f607a3649ae59c59aa6bf8cfb

**Comment by fnagel** [comment]
Just to make sure:

```
{
    "messages": [
        "The following errors were reported:",
        "Extension does not have a dependency for a supported version of TYPO3. See http:\/\/typo3.org\/news\/article\/announcing-ter-cleanup-process\/ for how to fix this. (0)\n"
    ]
}
```

is the TER response, right?

Your test release has different dependencies. Would you mind trying something similar to: 
https://github.com/fnagel/generic-gallery/blob/da491caea99202978cdd198a0ce022b80e1ca940/ext_emconf.php#L26-L28

**Comment by NamelessCoder** [comment]
I'll test anything you throw at me ;)

**Comment by fnagel** [comment]
<3

**Comment by NamelessCoder** [comment]
Forgot to say: you can check the response in the commit link I sent - the API posts it as a comment for each release commit.

**Comment by NamelessCoder** [comment]
https://github.com/NamelessCoder/uploadtest/commit/5264e99e6871c3a09792bf37fe173fffbc40319a

**Comment by NamelessCoder** [comment]
https://github.com/NamelessCoder/uploadtest/commit/d9f39c7ba20daf89c5854a07e2a0027f9496d20c

**Comment by fnagel** [comment]
Ahhh, ok. So what does that mean. Does it need the `cms` part?

**Comment by NamelessCoder** [comment]
https://github.com/NamelessCoder/uploadtest/commit/0531636dd32df16ed3887073a44049c47e8c343a

**Comment by NamelessCoder** [comment]
https://github.com/NamelessCoder/uploadtest/commit/32833a2a50db78b5375fb9ac6d59a174827cb9b6

**Comment by NamelessCoder** [comment]
AHA! Nailed it. It **must** have the `cms` entry, no version constraints required though. With that, it eats your `6.0.0-6.2.99` constraint raw :)

**Comment by fnagel** [comment]
WTF. Is this a brand new TER behavior? As https://github.com/fnagel/t3extblog/commit/d10760be3c34056342b2f80e071819e19a645c4f has no cms dependency and was successfully uploaded.

**Comment by fnagel** [comment]
So, need to force push my 1.0.0 tag :-/

**Comment by NamelessCoder** [comment]
I am pretty sure it is new, yes. Sucks a bit. I had actually planned on removing that silly empty constraint but definitely won't, now. I suspect it is the cause for the dual TYPO3 dependency (one with version, one without) on TER so I wanted to beautify that a bit.

> So, need to force push my 1.0.0 tag .-/

Ouch. Pain.

**Comment by NamelessCoder** [comment]
Got another recommendation for you (don't mean to spam but it might make sense here): if you use `fluidtypo3-development` in `require-dev` for your extension, the commands `./vendor/bin/setversion` and `./vendor/bin/upload` become available. No brainer to guess what they do - examples:

```
./vendor/bin/setversion 1.2.3 stable
./vendor/bin/upload . username password
```

After `composer install` inside extension folder.

**Comment by fnagel** [comment]
Added `cms` dependency and the deploy worked. 

I'm interested if my next release of t3extblog will work as there is no `cms` dependency but it worked 48h ago.

**Comment by NamelessCoder** [comment]
> I'm interested if my next release of t3extblog will work

Better go right ahead and add that dependency. Anything to avoid recreating tags.

**Comment by fnagel** [comment]
Yeeah, my plan is to use your whole auto magic PR and per commit code testing tools but I had some minor issues installing it on my server (provided by uberspace). Mostly a problem of lag of time to figure out proper configuration.

**Comment by NamelessCoder** [comment]
> Mostly a problem of lag of time to figure out proper configuration.

If I can help, let me know. The best hints I can give is that `composer install` should yell about any missing php modules and that you must have a personal access token in place or the API can't read the data from GitHub it needs when it is not in the payload (commit list, for example). With that, it should "just work" on any httpd with php 5.4+ using any integration.

**Comment by mbrodala** [comment]
@fnagel I didn't solve the issue but stopped to make useless releases for the sake of auto-release on TER instead. ;-) I'll give the `cms => ''` hack a try though.

**Comment by mbrodala** [comment]
[Looks good so far](https://travis-ci.org/pagemachine/cors/jobs/54549109#L276):

> Succesfully uploaded new version: 1.2.10
> Message #1: Please note that it might take a while (up to an hour) until your extension and the documentation appear on TYPO3.org.

Let's see if it really ends up on TER. ;-)

**Comment by fnagel** [comment]
Should work, did for me as soon as I added the `cms` dependency.

**Comment by mbrodala** [comment]
Yep, worked like a charm. Now if someone can make some sense out of this, that'd be awesome.

This looks a bit weird though:

![ter-dependencies-typo3-double](https://cloud.githubusercontent.com/assets/5037116/6664746/a53330d6-cbd2-11e4-87fc-b1193f0b5d2d.png)

**Comment by liayn** [comment]
Just to let you know, I encounter the same issue now using ext:developer or typo3.org upload form.
Last release 1 week ago worked without issues.
Adding the `cms` dependency does not help.

**Comment by NamelessCoder** [comment]
This is a bit weird. Are either of you involved with / in contact with the server team? It would be nice to learn exactly what is going on here - because imho it sounds like a bug that one **must** require both "typo3" with a specific version and "cms" with either no version or the same version as "typo3". It's been a good while since TYPO3 sites made sense without the "cms" extension installed...

**Comment by liayn** [comment]
I'm in touch with Thomas Löffler. He promised to get back to me tonight.

**Comment by liayn** [comment]
Ok the issue is resolved. The `cms` thing is not required at all. The issue was a change to the JSON of Core versions, which caused the version check of the emconf to fail.

**Comment by NamelessCoder** [comment]
Great to hear, including that `cms` is not needed as dependency! :)

**Comment by mbrodala** [comment]
@liayn Thanks for digging into this. I'll drop the pseudo-dependency. ;-)

**Comment by NamelessCoder** [comment]
Indeed, thanks to @liayn for the digging!

**Comment by mbrodala** [comment]
I'm getting this again right now:

> SOAP error: Extension does not have a dependency for a supported version of TYPO3. See http://typo3.org/news/article/announcing-ter-cleanup-process/ for how to fix this.

The `depends` section in `ext_emconf.php` still looks like in the initial post.

**Comment by fnagel** [comment]
Works for me here, released this yesterday: https://github.com/fnagel/generic-gallery/blob/d7f9d9929cbd43c9baa66d3cca74bf8c77674579/ext_emconf.php

Still using `cms` as a dependecy for this extension.

**Comment by NamelessCoder** [comment]
I created a release not more than a few days ago, also worked for it (extension key: site).

**Comment by mbrodala** [comment]
@fnagel I dropped the `cms` pseudo-dependency but adding it back indeed fixes the upload:

> Succesfully uploaded new version: x.y.z
> Message #1: Please note that it might take a while (up to an hour) until your extension and the documentation appear on TYPO3.org.

@NamelessCoder, @liayn  Any idea?

**Comment by NamelessCoder** [comment]
No ideas, but a fair amount of confusion. That restriction was removed... right?

**Comment by NamelessCoder** [comment]
This one was a succesful upload a couple of days ago: https://github.com/FluidTYPO3/site/blob/development/ext_emconf.php - no `cms` dependency.

**Comment by NamelessCoder** [comment]
Hang on here. Is this because you are solely compatible with 6.2 and TER then does some magic that depends on `cms` when you have a 6.2.x max, whereas `typo3` is used when extension is compatible with 7.x max? Just guessing. Nothing really seems to explain this except some magic behavior depending on something in the uploaded array and there's not a whole lot of metadata to go on.

**Comment by mbrodala** [comment]
That'd be my guess too and I could give it a try with [another extension](https://github.com/pagemachine/hairu/blob/1.3.2/ext_emconf.php) which was tested with TYPO3 7.4 already but I only have one shot since a published version is published. I'd prefer @liayn shedding some light on this.

**Comment by liayn** [comment]
Generally cms shouldn't be used for 7 anymore, but there is a fallback in EM, when it is still present.
In terms of TER, I'm the wrong person. Please ask T. Löffler in Slack or take a look at the source code, what is going on there.

**Comment by fnagel** [comment]
Running into this issue again. Any news / insights in this @mbrodala @NamelessCoder?

**Comment by mbrodala** [comment]
@fnagel That's odd since I haven't encountered this issue again. I just did an upload recently which [went just fine](https://travis-ci.org/pagemachine/cors/jobs/114207882#L691).

This is the relevant section in [my `ext_emconf.php`](https://github.com/pagemachine/cors/blob/506c0ebdc659395c73a564969362cc38b14a556e/ext_emconf.php#L13):

``` php
<?php
$EM_CONF[$_EXTKEY] = array(
  // ...
  'constraints' => array(
    'depends' => array(
      'typo3' => '6.2.0-7.6.99',
    ),
    // ...
  ),
);
```

**Comment by fnagel** [comment]
> Running into this issue again

Read: Thought about removing the `cms` key, not actually failed uploading. Sorry for the confusion.

I will give it another try soon and report back here. Thanks for the quick response!

**Comment by NamelessCoder** [comment]
Last uploads of fluidpages and fluidcontent no longer have the "cms" dependency and worked fine. TER still rejects extensions trying to say they're compatible with TYPO3 8.0 (imho TER should allow that as soon as `-dev` of a TYPO3 version is created but that's another topic).

PS: take care to remove it from both the dependencies _array_ and the dependencies _CSV_!

**Comment by fnagel** [comment]
I've successfully released [two](https://github.com/fnagel/generic-gallery/blob/28d01d8ad4b96101b7a25f2f0902b6c39b045677/ext_emconf.php) [extension](https://github.com/fnagel/t3extblog/blob/d6f668e417dbf4443b9e50364c8976217047638c/ext_emconf.php) without the `cms` dependency. Seems save to remove.
