### ISSUE TITLE
No usage help text output for setversion

### ISSUE THREAD

**Issue by liayn** [NamelessCoder/typo3-repository-client#2]
calling `setversion` without parameters results in PHP warnings.
The check for less than 2 argv is missing.

**Comment by NamelessCoder** [comment]
Confirmed - simple fix; will take care of that soon if you don't beat me to it!

**Comment by liayn** [comment]
No hurry. ;-)

**Comment by helhum** [comment]
Should be fixed with #9

**Comment by NamelessCoder** [comment]
Fixed and then some - #9 and https://github.com/NamelessCoder/typo3-repository-client#version-updater-local
