### ISSUE TITLE
Getting "Runtime error: Directory name must not be empty."

### ISSUE THREAD

**Issue by mbrodala** [NamelessCoder/typo3-repository-client#4]
Using the `upload` script with valid arguments always only gives me the following error:

> Runtime error: Directory name must not be empty.

This seems to be triggered by the `DirectoryIterator`. The directory was given as a absolute path which definitely exists.

**Comment by NamelessCoder** [comment]
Hi @mbrodala - are you by any chance on Windows?

**Comment by mbrodala** [comment]
No, everything was executed on a *nix environment. I tried all of `.`, `$PWD` and the fully spelled absolute path to no avail. This did work quite fine a while ago though.

**Comment by mbrodala** [comment]
Here's a full transcript using our [hairu](https://github.com/pagemachine/hairu) extension:

```
$ composer create-project pagemachine/hairu:dev-master
Installing pagemachine/hairu (dev-master cfd05b9468504acd4dbbf8661bf80e5fe43b07a1)
  - Installing pagemachine/hairu (dev-master master)
    Cloning master

Created project in /tmp/hairu
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing namelesscoder/typo3-repository-client (1.0.5)
    Downloading: 100%

Writing lock file
Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]?
$ cd hairu/
/hairu$ .build/bin/upload foo bar . "Test"
Runtime error: Directory name must not be empty.
```

**Comment by NamelessCoder** [comment]
Ah, now I see the issue. Maybe the doc is wrong, but the correct usage is:

`./bin/upload . foo bar "Comment"` - the reason you are getting "directory name must not be empty" is that `realpath($dir)` is used to resolve symlinks and it returns `FALSE` when given a folder that doesn't exist - in the case of your command, it tries to find the folder `./foo` in the build directory and thinks your password is a single dot. Put the directory first and I'm betting it solves itself ;)

**Comment by NamelessCoder** [comment]
Yep, argument order in help text was all wrong:

https://github.com/NamelessCoder/typo3-repository-client/commit/39759d9d58aeee31d75f6657b4df79a6d81d53b6

**Comment by mbrodala** [comment]
Not sure if this really is the issue since I apparently actually use the correct order in my [deployment script triggered by Travis](https://www.snip2code.com/Snippet/376713/Travis-after_success-deployasaur-us-scri). I'll try to execute it manually.

**Comment by mbrodala** [comment]
Yep, the script invocation is fine. I've encountered a different issue now and added this in #5.
