### ISSUE TITLE
SOAP error: Failed Sending HTTP SOAP request

### ISSUE THREAD

**Issue by mbrodala** [NamelessCoder/typo3-repository-client#5]
Trying to `upload` an extension currently fails:

> PHP Notice:  SoapClient::__doRequest(): send of 8192 bytes failed with errno=11 Resource temporarily unavailable in /.../vendor/namelesscoder/typo3-repository-client/src/Connection.php on line 41
> 
> Notice: SoapClient::__doRequest(): send of 8192 bytes failed with errno=11 Resource temporarily unavailable in /.../vendor/namelesscoder/typo3-repository-client/src/Connection.php on line 41
> SOAP error: Failed Sending HTTP SOAP request

Maybe there's something off with the TER SOAP interface?

**Comment by NamelessCoder** [comment]
Hi Mathias - have you been able to reproduce this since? Like the error message says, it sounds like temporary unavailability (maybe a service restart at an unlucky time during your upload).

**Comment by mbrodala** [comment]
Looks better now but now I get the dreaded "supported version error" from #1 again, the `depends` are the still the same.

**Comment by NamelessCoder** [comment]
I assume you've removed `cms` from the list of dependencies? And that all your dependency versions have both a min- and max version? And that the max supported TYPO3 versions is actually one that is released?
- Just going through the usual causes ;)

**Comment by mbrodala** [comment]
Just commented in #1, thanks for asking. ;-)
