### ISSUE TITLE
Suggests array is not uploaded

### ISSUE THREAD

**Issue by helhum** [NamelessCoder/typo3-repository-client#7]
Looking at https://github.com/NamelessCoder/typo3-repository-client/blob/master/src/ExtensionUploadPacker.php#L107-L108 it seems that the suggests array is not prepared for upload. Any reasons for that?

**Comment by NamelessCoder** [comment]
Hi Helmut,

Hmm, I seem to recall something about the upload failing always with the same exception if said array was included - but that was almost a year ago and I never tried it since. If TER accepts it then we should of course include the array.

**Comment by helhum** [comment]
I never heard of such TER behavior. from reading the TER code, it just works and the information is added. The thing is, the suggest part actually influences the behavior of TYPO3, as it is used to influence the ordering of extensions in package states. Not providing this info in TER makes the extension incomplete (and at worst non functional)
